# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        monitor:
          github:
            enabled: true
        git:
          username: goelprateek@gmail.com
          password: mln!Soni12
          clone-on-start: true
          uri: https://github.com/goelprateek/microservices-configuration.git
          force-pull: true
        default-profile: dev
        default-label: dev
  kafka:
     bootstrap-servers: localhost:9092




server:
  port: 7070

security:
  basic:
    enabled: false

---

spring:
  profiles: docker
  kafka:
    bootstrap-servers: ${KAFKA_SERVICE_URL}
server:
  port: ${SERVICE_PORT}
