

spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        monitor:
          github:
            enabled: true
        git:
          username: goelprateek@gmail.com
          password: mln!Soni12
          clone-on-start: true
          uri: https://github.com/goelprateek/microservices-configuration.git
  kafka:
     bootstrap-servers: 192.168.99.100:9092



server:
  port: 9094


security:
  basic:
    enabled: false

