

spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        monitor:
          github:
            enabled: true
        git:
          username: goelprateek@gmail.com
          password: mln!Soni12
          clone-on-start: true
          uri: https://github.com/goelprateek/microservices-configuration.git
          force-pull: true
        default-profile: dev
        default-label: dev

  kafka:
     bootstrap-servers: 192.168.99.100:9092




server:
  port: 7070


security:
  basic:
    enabled: false

