# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
spring:
  profiles:
    active: dev
    include: swagger


management:
  security:
    roles: ADMIN
  context-path: /management

oauth2:
    signature-verification:
        public-key-endpoint-uri: http://auth-server/uaa/oauth/token_key
        #ttl for public keys to verify JWT tokens (in ms)
        ttl: 3600000
        #max. rate at which public keys will be fetched (in ms)
        public-key-refresh-rate-limit: 10000
    web-client-configuration:
        #keep in sync with UAA configuration
        client-id: web_app
        secret: changeit
        # Controls session expiration due to inactivity (ignored for remember-me).
        # Negative values disable session inactivity expiration.
        session-timeout-in-seconds: 1800

# ===================================================================
# Gateway specific properties
# ===================================================================

gonogo:
  gateway:
    rate-limiting:
      enabled: true
      limit: 10000
      duration-in-seconds: 3600
    authorized-microservices-endpoints: # Access Control Policy, if left empty for a route, all endpoints will be accessible
          app1: /api,/v2/api-docs # recommended dev configuration
  cache: # Cache configuration
    hazelcast: # Hazelcast distributed cache
      time-to-live-seconds: 3600
      backup-count: 1
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization"
    allow-credentials: true
    max-age: 1800
  logging:
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: true
      host: localhost
      port: 5000
      queue-size: 512
  security:
    client-authorization:
      access-token-uri: http://auth-server/uaa/oauth/token
      token-service-id: auth-server
      client-id: internal
      client-secret: internal