# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  aop:
    proxyTargetClass: true
  sleuth:
    sampler:
      percentage: 1.0
    web:
      skip-pattern: (.+favicon.*)




# See http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html
zuul: # those values must be configured depending on the application specific needs
  host:
    max-total-connections: 1000
    max-per-route-connections: 100
  semaphore:
    max-semaphores: 500


# ===================================================================
# GoNoGo specific properties
# ===================================================================
gonogo:
  swagger:
    default-include-pattern: /api/.*
    title: zuulproxy API
    description: zuulproxy API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license:
    license-url:

---
spring:
  profiles: docker
server:
  port: ${SERVICE_PORT}
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: ${REGISTRY_URL}