version: '2.1'

services:

# adding zookeeper service on port 2181 [default port]
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

# adding kafka service on port 9092 [default port]
  kafka:
    image: wurstmeister/kafka:0.10.1.1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "socialCloudBus:1:1"
    healthcheck:
      test: ["CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list"]
      interval: 10s
      timeout: 5s
      retries: 10


#  adding elasticsearch
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
      ports:
        - "9200:9200"
      environment:
        - "xpack.security.enabled=false"
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 10s
        timeout: 5s
        retries: 10

  kibana:
      image: docker.elastic.co/kibana/kibana:5.2.2
      ports:
        - "5601:5601"
      environment:
        - "xpack.security.enabled=false"
      depends_on:
        elasticsearch:
          condition: service_healthy

  logstash:
      image: docker.elastic.co/logstash/logstash:5.2.2
      ports:
        - "5000:5000"
      volumes:
        - $PWD/elk-config:/elk-config
      command: logstash -f /elk-config/logstash.config
      depends_on:
        elasticsearch:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080"]
        interval: 10s
        timeout: 5s
        retries: 10


# adding mongodb service on port 27017 [default port ] having volume attached to host machine mongo data directory
  mongodb:
    image: mongo:3.4
    expose:
      - 27017
    ports:
      - "39017:27017"
    volumes:
      - /home/prateek/data/db:/data/db
    command: mongod --smallfiles
    logging:
      driver: "json-file"

# adding configuration server on port 7070
  configuration-server:
    image: gonogo/configuration-server
    environment:
      SERVICE_PORT: 7070
      KAFKA_SERVICE_URL: http://kafka:9092
    depends_on:
      - kafka
    links:
      - kafka:kafka

# adding service registry on port 7071
  service-registry:
      image: gonogo/service-registry
      environment:
        SERVICE_HOST: registry
        SERVICE_PORT: 7071
      depends_on:
        - configuration-server
      links:
        - configuration-server:configuration-server
      ports:
        - "7071:7071"

# adding UAA server on port 7072 , which depends on mongodb , kafka, zookeeper
  uaa-server:
    image: gonogo/uaa-server
    logging:
      driver: json-file
    depends_on:
      - mongodb
      - kafka
      - configuration-server
      - service-registry
    environment:
      SERVICE_PORT: 7072
      REGISTRY_URL: http://service-registry:7071/eureka
      CONFIG_URL: http://configuration-server:7070
    links:
      - mongodb:mongodb
      - configuration-server:configuration-server
      - service-registry:service-registry


# adding micro proxy gateway for gonogo on port 8080, which depends on uaa-server, service-registry, configuration-service
  gateway:
    image: gonogo/gateway
    logging:
      driver: json-file
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - logstash
      - uaa-server
      - zookeeper
      - kafka
    links:
      - configuration-server:configuration-server
      - service-registry:service-registry
      - uaa-server:uaa-server
    environment:
      SERVICE_PORT: 8080
      REGISTRY_URL: http://service-registry:7071/eureka

# adding resource server on port 7075
  resource-server:
    image: gonogo/resource-server
    logging:
      driver: json-file
    links:
      - configuration-server:configuration-server
      - service-registry:service-registry
      - uaa-server:uaa-server
    environment:
      SERVICE_PORT: 7075
      REGISTRY_URL: http://service-registry:7071/eureka

# adding social client on port 7076
  social-client:
    image: gonogo/social-client
    logging:
      driver: json-file
    links:
      - service-registry:service-registry
    environment:
      SERVICE_PORT: 7076
      REGISTRY_URL: http://service-registry:7071/eureka

