version: '2.1'

services:
#  adding elasticsearch
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
      ports:
        - "9200:9200"
      environment:
        - "xpack.security.enabled=false"
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 10s
        timeout: 5s
        retries: 10

  kibana:
      image: docker.elastic.co/kibana/kibana:5.2.2
      ports:
        - "5601:5601"
      environment:
        - "xpack.security.enabled=false"
      depends_on:
        elasticsearch:
          condition: service_healthy

  logstash:
      image: docker.elastic.co/logstash/logstash:5.2.2
      ports:
        - 5000:5000
        - 5000:5000/udp
      volumes:
        - $PWD/elk-config:/elk-config
      command: logstash -f /elk-config/logstash.config
      depends_on:
        elasticsearch:
          condition: service_healthy
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080"]
        interval: 10s
        timeout: 5s
        retries: 10