# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

gng:
  resource:
    access-token-validity: 30
    refresh-token-validity: 86400
    localValidation: true
    checkTokenUri: http://localhost:7072/uaa/oauth/token_key
  resource-server-properties:
    id: rest_api

---
spring:
  profiles: docker
server:
  port: ${SERVICE_PORT}
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: ${REGISTRY_URL}